from typing import Optional

class AppDirs:
    def __init__(
        self,
        appname: Optional[str] = None,
        appauthor: Optional[str] = None,
        version: Optional[str] = None,
        roaming: bool = False,
        multipath: bool = False,
    ) -> None: ...
    @property
    def user_data_dir(self) -> str: ...
    @property
    def site_data_dir(self) -> str: ...
    @property
    def user_config_dir(self) -> str: ...
    @property
    def site_config_dir(self) -> str: ...
    @property
    def user_cache_dir(self) -> str: ...
    @property
    def user_state_dir(self) -> str: ...
    @property
    def user_log_dir(self) -> str: ...
